version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  backend:
    build:
      context: ./backend
    command: "rails s -p 80 -b '0.0.0.0'"
    volumes:
      - ./backend:/app
      - bundle:/usr/local/bundle
    ports:
      - "80:80"
    depends_on:
      - db
volumes:
  postgresql:
  bundle:
